### ISSUE TITLE
关于内容跟随listview一起滚动的问题

### ISSUE THREAD

**Issue by jinliang666** [SmallStoneSK/flutter_training_app#1]
您好 我这边想实现一个 类似 SliverAppBar 跟随listview滚动的 效果，但是需求是SliverAppBar是一个自定义的Widget 类似支付宝首页实现 请问您有什么好的解决方式么

**Comment by SmallStoneSK** [comment]
`SliverAppBar`也是基于`SliverPersistentHeader`实现的，你可以自己实现一个类似`SliverAppBar`的组件，这样`build`的部分就由你自己控制了。你可以跟进`SliverAppBar`的源码看下它是怎么封装的，也可以简单参考下我之前写的这篇[文章](https://github.com/SmallStoneSK/Blog/issues/18)。

**Comment by jinliang666** [comment]
好非常感谢您
